'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace BlogServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BlogPost", [Namespace]:="http://schemas.datacontract.org/2004/07/BlogLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BlogPost
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostedAtField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Content() As String
            Get
                Return Me.ContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContentField, value) <> true) Then
                    Me.ContentField = value
                    Me.RaisePropertyChanged("Content")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostedAt() As Date
            Get
                Return Me.PostedAtField
            End Get
            Set
                If (Me.PostedAtField.Equals(value) <> true) Then
                    Me.PostedAtField = value
                    Me.RaisePropertyChanged("PostedAt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="BlogServiceRef.IBlogService")>  _
    Public Interface IBlogService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlogService/AddPost", ReplyAction:="http://tempuri.org/IBlogService/AddPostResponse")>  _
        Function AddPost(ByVal title As String, ByVal content As String) As BlogServiceRef.BlogPost
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlogService/AddPost", ReplyAction:="http://tempuri.org/IBlogService/AddPostResponse")>  _
        Function AddPostAsync(ByVal title As String, ByVal content As String) As System.Threading.Tasks.Task(Of BlogServiceRef.BlogPost)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlogService/GetPosts", ReplyAction:="http://tempuri.org/IBlogService/GetPostsResponse")>  _
        Function GetPosts() As BlogServiceRef.BlogPost()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlogService/GetPosts", ReplyAction:="http://tempuri.org/IBlogService/GetPostsResponse")>  _
        Function GetPostsAsync() As System.Threading.Tasks.Task(Of BlogServiceRef.BlogPost())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBlogServiceChannel
        Inherits BlogServiceRef.IBlogService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BlogServiceClient
        Inherits System.ServiceModel.ClientBase(Of BlogServiceRef.IBlogService)
        Implements BlogServiceRef.IBlogService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AddPost(ByVal title As String, ByVal content As String) As BlogServiceRef.BlogPost Implements BlogServiceRef.IBlogService.AddPost
            Return MyBase.Channel.AddPost(title, content)
        End Function
        
        Public Function AddPostAsync(ByVal title As String, ByVal content As String) As System.Threading.Tasks.Task(Of BlogServiceRef.BlogPost) Implements BlogServiceRef.IBlogService.AddPostAsync
            Return MyBase.Channel.AddPostAsync(title, content)
        End Function
        
        Public Function GetPosts() As BlogServiceRef.BlogPost() Implements BlogServiceRef.IBlogService.GetPosts
            Return MyBase.Channel.GetPosts
        End Function
        
        Public Function GetPostsAsync() As System.Threading.Tasks.Task(Of BlogServiceRef.BlogPost()) Implements BlogServiceRef.IBlogService.GetPostsAsync
            Return MyBase.Channel.GetPostsAsync
        End Function
    End Class
End Namespace
